[package]
name = "wham"
version = "0.9.0"
authors = ["D. Bauer <bauer@bio.tu-darmstadt.de>"]

[dependencies]
clap = {version="2.32.0", features=['yaml']}
error-chain = "0.12.0"
rand = "0.5.5"
GSL = "1.0.0"

[profile.release]
opt-level = 2

[features]
default = ["GSL/v2"]