[package]
name = "wham"
version = "0.9.3"
authors = ["D. Bauer <bauer@bio.tu-darmstadt.de>"]
description = "An implementation of the weighted histogram analysis method"
license = "GPL-3.0"
repository = "https://github.com/danijoo/WHAM"

[dependencies]
clap = {version="2.32.0", features=['yaml']}
error-chain = "0.12.0"
rand = "0.5.5"
GSL = "1.0.0"
rayon = "1.0.3"

[profile.release]
opt-level = 2

[features]
default = ["GSL/v2"]
